version: '3'
services:
#mssql docker
  autoservice-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    expose:
      - 1433
    networks:
      - autoservicenet

  autoservice-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:DefaultConnection=Server=autoservice-sql,1433;Database=AutoService;User=sa;Password=QWElkj132!;ConnectRetryCount=0; TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 7264:7264
    networks:
      - autoservicenet      
    links:
      - autoservice-sql
    depends_on:
      - autoservice-sql
      
  autoservice-identity-api:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./AutoService.IdentityServer/Dockerfile  
    environment:
      - ConnectionStrings:AutoService=Server=autoservice-sql,1433;Database=AutoService;User=sa;Password=QWElkj132!;ConnectRetryCount=0; TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 7179:7179
    networks:
      - autoservicenet      
    links:
      - autoservice-sql
    depends_on:
      - autoservice-sql    
  
networks:
  autoservicenet:
    driver: bridge      