// <auto-generated />
using System;
using AutoService.Data.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoService.Data.Migrations
{
    [DbContext(typeof(AutoServiceContext))]
    partial class AutoServiceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AutoService.Data.Entities.ClientData.ProfilePhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Extension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileSystemPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Format")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResolutionUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SizeInBytes")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Width")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Xresolution")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Yresolution")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ProfilePhotos");
                });

            modelBuilder.Entity("AutoService.Data.Entities.ServiceData.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsOccupied")
                        .HasColumnType("bit");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = new Guid("813a46d4-a59a-47ed-a88f-3143456e6f13"),
                            Date = new DateTime(2024, 2, 28, 20, 13, 21, 507, DateTimeKind.Local).AddTicks(6942),
                            IsOccupied = true,
                            RequestId = 1
                        },
                        new
                        {
                            Id = 2,
                            ClientId = new Guid("813a46d4-a59a-47ed-a88f-3143456e6f13"),
                            Date = new DateTime(2024, 2, 28, 19, 13, 21, 507, DateTimeKind.Utc).AddTicks(6945),
                            IsOccupied = false,
                            RequestId = 2
                        },
                        new
                        {
                            Id = 3,
                            ClientId = new Guid("813a46d4-a59a-47ed-a88f-3143456e6f13"),
                            Date = new DateTime(2024, 2, 28, 20, 13, 21, 507, DateTimeKind.Local).AddTicks(6946),
                            IsOccupied = true,
                            RequestId = 3
                        },
                        new
                        {
                            Id = 4,
                            ClientId = new Guid("813a46d4-a59a-47ed-a88f-3143456e6f13"),
                            Date = new DateTime(2024, 2, 28, 20, 13, 21, 507, DateTimeKind.Local).AddTicks(6948),
                            IsOccupied = false,
                            RequestId = 4
                        });
                });

            modelBuilder.Entity("AutoService.Data.Entities.ServiceData.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Checks"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Changes"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tuning"
                        });
                });

            modelBuilder.Entity("AutoService.Data.Entities.ServiceData.Request", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomRequest")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DateCompleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateRequested")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique()
                        .HasFilter("[AppointmentId] IS NOT NULL");

                    b.HasIndex("ClientId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Request");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentId = 1,
                            ClientId = new Guid("813a46d4-a59a-47ed-a88f-3143456e6f13"),
                            CustomRequest = "Change tires",
                            DateCompleted = new DateTime(2024, 2, 28, 19, 13, 21, 507, DateTimeKind.Utc).AddTicks(6927),
                            DateRequested = new DateTime(2024, 2, 28, 19, 13, 21, 507, DateTimeKind.Utc).AddTicks(6928),
                            Status = 2,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 2,
                            AppointmentId = 2,
                            ClientId = new Guid("813a46d4-a59a-47ed-a88f-3143456e6f13"),
                            CustomRequest = "Change window",
                            DateCompleted = new DateTime(2024, 2, 28, 19, 13, 21, 507, DateTimeKind.Utc).AddTicks(6930),
                            DateRequested = new DateTime(2024, 2, 28, 19, 13, 21, 507, DateTimeKind.Utc).AddTicks(6930),
                            Status = 5,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 3,
                            AppointmentId = 3,
                            ClientId = new Guid("813a46d4-a59a-47ed-a88f-3143456e6f13"),
                            CustomRequest = "Change bumper",
                            DateCompleted = new DateTime(2024, 2, 28, 19, 13, 21, 507, DateTimeKind.Utc).AddTicks(6931),
                            DateRequested = new DateTime(2024, 2, 28, 19, 13, 21, 507, DateTimeKind.Utc).AddTicks(6932),
                            Status = 3,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 4,
                            AppointmentId = 4,
                            ClientId = new Guid("813a46d4-a59a-47ed-a88f-3143456e6f13"),
                            CustomRequest = "Change rims",
                            DateCompleted = new DateTime(2024, 2, 28, 19, 13, 21, 507, DateTimeKind.Utc).AddTicks(6933),
                            DateRequested = new DateTime(2024, 2, 28, 19, 13, 21, 507, DateTimeKind.Utc).AddTicks(6933),
                            Status = 4,
                            VehicleId = 1
                        });
                });

            modelBuilder.Entity("AutoService.Data.Entities.ServiceData.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            IsActive = true,
                            Name = "Change oil",
                            Price = 80m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            IsActive = true,
                            Name = "Change brakes",
                            Price = 250m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            IsActive = true,
                            Name = "Check lights",
                            Price = 5m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            IsActive = true,
                            Name = "ECU Tune",
                            Price = 300m
                        });
                });

            modelBuilder.Entity("AutoService.Data.Entities.ServiceData.ServiceRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.HasIndex("ServiceId");

                    b.ToTable("ServiceRequest");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RequestId = 1,
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 2,
                            RequestId = 1,
                            ServiceId = 2
                        },
                        new
                        {
                            Id = 3,
                            RequestId = 2,
                            ServiceId = 3
                        },
                        new
                        {
                            Id = 4,
                            RequestId = 2,
                            ServiceId = 4
                        },
                        new
                        {
                            Id = 5,
                            RequestId = 3,
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 6,
                            RequestId = 3,
                            ServiceId = 2
                        },
                        new
                        {
                            Id = 7,
                            RequestId = 3,
                            ServiceId = 3
                        },
                        new
                        {
                            Id = 8,
                            RequestId = 4,
                            ServiceId = 1
                        });
                });

            modelBuilder.Entity("AutoService.Data.Entities.ServiceData.ServicesPerformed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("RecordId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecordId");

                    b.HasIndex("ServiceId");

                    b.ToTable("ServicesPerformed");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RecordId = 1,
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 2,
                            RecordId = 1,
                            ServiceId = 2
                        },
                        new
                        {
                            Id = 3,
                            RecordId = 1,
                            ServiceId = 3
                        },
                        new
                        {
                            Id = 4,
                            RecordId = 1,
                            ServiceId = 4
                        },
                        new
                        {
                            Id = 5,
                            RecordId = 2,
                            ServiceId = 3
                        },
                        new
                        {
                            Id = 6,
                            RecordId = 2,
                            ServiceId = 1
                        });
                });

            modelBuilder.Entity("AutoService.Data.Entities.UserData.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Role", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b907ae86-1b23-4a25-85c7-0c651f5e1d3d"),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("9f4392a8-80bc-4c4f-9a6a-8d2c6c875f84"),
                            Name = "Employee"
                        },
                        new
                        {
                            Id = new Guid("c6c0e6d5-1a11-4b25-96a2-1989e24a2d6d"),
                            Name = "Client"
                        });
                });

            modelBuilder.Entity("AutoService.Data.Entities.UserData.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool?>("Active")
                        .HasColumnType("bit");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("PostalCode")
                        .HasColumnType("int");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("RoleId");

                    b.ToTable("User", "dbo");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b8396f1d-a29a-4856-a4c1-1312dc97a4a1"),
                            AccessFailedCount = 0,
                            Active = true,
                            Address = "Ulica 2",
                            BirthDate = new DateTime(2000, 1, 11, 16, 22, 29, 961, DateTimeKind.Unspecified),
                            City = "Mostar",
                            ConcurrencyStamp = "97e229af-2604-4b7c-b579-d44e43b88576",
                            CreatedDate = new DateTime(2024, 2, 7, 17, 26, 40, 899, DateTimeKind.Unspecified).AddTicks(9869),
                            Email = "employee@employee.com",
                            EmailConfirmed = false,
                            FirstName = "Employee",
                            Gender = 1,
                            LastName = "User",
                            LockoutEnabled = false,
                            ModifiedDate = new DateTime(2024, 2, 7, 17, 26, 40, 899, DateTimeKind.Unspecified).AddTicks(9930),
                            NormalizedEmail = "EMPLOYEE@EMPLOYEE.COM",
                            NormalizedUserName = "EMPLOYEE",
                            PasswordHash = "AQAAAAIAAYagAAAAEEIHvjeCGSTaZfqUVK9IC/ONuj5fJj5vKIhHnJkXRWgMCEspYS9/+gr3DBICkveXKg==",
                            PhoneNumber = "123456789",
                            PhoneNumberConfirmed = false,
                            PostalCode = 88104,
                            RoleId = new Guid("9f4392a8-80bc-4c4f-9a6a-8d2c6c875f84"),
                            SecurityStamp = "2bb56497-5c49-4c01-8bc7-e2df21ef5d53",
                            TwoFactorEnabled = false,
                            UserName = "EMPLOYEE"
                        },
                        new
                        {
                            Id = new Guid("f760ee5c-435b-4875-91a5-21a6a554513b"),
                            AccessFailedCount = 0,
                            Active = true,
                            Address = "Ulica 1",
                            BirthDate = new DateTime(2000, 1, 1, 16, 22, 29, 961, DateTimeKind.Unspecified),
                            City = "Mostar",
                            ConcurrencyStamp = "2ee39f74-519d-400f-bb89-c937f284b676",
                            CreatedDate = new DateTime(2024, 2, 7, 17, 24, 53, 422, DateTimeKind.Unspecified).AddTicks(1253),
                            Email = "admin@admin.com",
                            EmailConfirmed = false,
                            FirstName = "Admin",
                            Gender = 1,
                            LastName = "User",
                            LockoutEnabled = false,
                            ModifiedDate = new DateTime(2024, 2, 7, 17, 24, 53, 422, DateTimeKind.Unspecified).AddTicks(1765),
                            NormalizedEmail = "ADMIN@ADMIN.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAEI9PHasKoFp5DwWoGI8pTvKMeEUkZzfCkdtjIVgv1IWGNUMP9gHa01RFqELzQq5isw==",
                            PhoneNumber = "123456789",
                            PhoneNumberConfirmed = false,
                            PostalCode = 88000,
                            RoleId = new Guid("b907ae86-1b23-4a25-85c7-0c651f5e1d3d"),
                            SecurityStamp = "76cbb512-37af-4f7a-aef4-4b52eb2c7618",
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        },
                        new
                        {
                            Id = new Guid("813a46d4-a59a-47ed-a88f-3143456e6f13"),
                            AccessFailedCount = 0,
                            Active = true,
                            Address = "Ulica 3",
                            BirthDate = new DateTime(1998, 1, 4, 16, 22, 29, 961, DateTimeKind.Unspecified),
                            City = "Sarajevo",
                            ConcurrencyStamp = "650492b3-5975-4a30-b796-b27c56a065a3",
                            CreatedDate = new DateTime(2024, 2, 7, 17, 27, 27, 331, DateTimeKind.Unspecified).AddTicks(607),
                            Email = "client@client.com",
                            EmailConfirmed = false,
                            FirstName = "Client",
                            Gender = 2,
                            LastName = "User",
                            LockoutEnabled = false,
                            ModifiedDate = new DateTime(2024, 2, 7, 17, 27, 27, 331, DateTimeKind.Unspecified).AddTicks(637),
                            NormalizedEmail = "CLIENT@CLIENT.COM",
                            NormalizedUserName = "CLIENT",
                            PasswordHash = "AQAAAAIAAYagAAAAEIPOmlsV57rPJlEsDCfu4rsP2GBDN7KXIcFymvHL2ZLzlyCbzIn+LGx6DSCe6BV2og==",
                            PhoneNumber = "123456789",
                            PhoneNumberConfirmed = false,
                            PostalCode = 88104,
                            RoleId = new Guid("c6c0e6d5-1a11-4b25-96a2-1989e24a2d6d"),
                            SecurityStamp = "f5f9fa28-8f00-45a5-b3d9-e0921a1a104d",
                            TwoFactorEnabled = false,
                            UserName = "Client"
                        });
                });

            modelBuilder.Entity("AutoService.Data.Entities.VehicleData.TransmissionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TransmissionTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Manual"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Automatic"
                        });
                });

            modelBuilder.Entity("AutoService.Data.Entities.VehicleData.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("FuelTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManufactureYear")
                        .HasColumnType("int");

                    b.Property<int?>("Mileage")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("TransmissionTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("VehicleTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("FuelTypeId");

                    b.HasIndex("TransmissionTypeId");

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = new Guid("813a46d4-a59a-47ed-a88f-3143456e6f13"),
                            FuelTypeId = 2,
                            Make = "Peugeot",
                            ManufactureYear = 2016,
                            Mileage = 195123,
                            Model = "308",
                            Status = 2,
                            TransmissionTypeId = 1,
                            VehicleTypeId = 2,
                            Vin = "1231AKHJKHJ1213JH"
                        },
                        new
                        {
                            Id = 2,
                            ClientId = new Guid("813a46d4-a59a-47ed-a88f-3143456e6f13"),
                            FuelTypeId = 1,
                            Make = "Toyota",
                            ManufactureYear = 2008,
                            Mileage = 18590,
                            Model = "Yaris",
                            Status = 4,
                            TransmissionTypeId = 1,
                            VehicleTypeId = 2,
                            Vin = "12151AKGHEQRH15121JH"
                        });
                });

            modelBuilder.Entity("AutoService.Data.Entities.VehicleData.VehicleFuelType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VehicleFuelTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Petrol"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Diesel"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Electric"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Hybrid"
                        });
                });

            modelBuilder.Entity("AutoService.Data.Entities.VehicleData.VehicleServiceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal?>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MileageAtTimeOfService")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleServiceRecords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 1500m,
                            Date = new DateTime(2024, 2, 28, 20, 13, 21, 507, DateTimeKind.Local).AddTicks(6851),
                            MileageAtTimeOfService = 185100,
                            Notes = "Found broken light",
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 2,
                            Cost = 500m,
                            Date = new DateTime(2024, 2, 28, 20, 13, 21, 507, DateTimeKind.Local).AddTicks(6875),
                            MileageAtTimeOfService = 17800,
                            Notes = "",
                            VehicleId = 2
                        });
                });

            modelBuilder.Entity("AutoService.Data.Entities.VehicleData.VehicleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VehicleTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sedan"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hatchback"
                        },
                        new
                        {
                            Id = 3,
                            Name = "SUV"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Coupe"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Minivan"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Convertible"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Station wagon"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Crossover"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaim", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaim", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogin", "dbo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserToken", "dbo");
                });

            modelBuilder.Entity("AutoService.Data.Entities.ClientData.Client", b =>
                {
                    b.HasBaseType("AutoService.Data.Entities.UserData.User");

                    b.HasDiscriminator().HasValue("Client");
                });

            modelBuilder.Entity("AutoService.Data.Entities.ServiceData.Appointment", b =>
                {
                    b.HasOne("AutoService.Data.Entities.ClientData.Client", "Client")
                        .WithMany("Appointments")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("AutoService.Data.Entities.ServiceData.Request", b =>
                {
                    b.HasOne("AutoService.Data.Entities.ServiceData.Appointment", "Appointment")
                        .WithOne("Request")
                        .HasForeignKey("AutoService.Data.Entities.ServiceData.Request", "AppointmentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("AutoService.Data.Entities.ClientData.Client", "Client")
                        .WithMany("Requests")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AutoService.Data.Entities.VehicleData.Vehicle", "Vehicle")
                        .WithMany("Requests")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Appointment");

                    b.Navigation("Client");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("AutoService.Data.Entities.ServiceData.Service", b =>
                {
                    b.HasOne("AutoService.Data.Entities.ServiceData.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AutoService.Data.Entities.ServiceData.ServiceRequest", b =>
                {
                    b.HasOne("AutoService.Data.Entities.ServiceData.Request", "Request")
                        .WithMany("ServiceRequests")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoService.Data.Entities.ServiceData.Service", "Service")
                        .WithMany("ServiceRequests")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Request");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("AutoService.Data.Entities.ServiceData.ServicesPerformed", b =>
                {
                    b.HasOne("AutoService.Data.Entities.VehicleData.VehicleServiceRecord", "Record")
                        .WithMany("ServicesPerformeds")
                        .HasForeignKey("RecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoService.Data.Entities.ServiceData.Service", "Service")
                        .WithMany("ServicesPerformeds")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Record");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("AutoService.Data.Entities.UserData.User", b =>
                {
                    b.HasOne("AutoService.Data.Entities.UserData.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AutoService.Data.Entities.VehicleData.Vehicle", b =>
                {
                    b.HasOne("AutoService.Data.Entities.ClientData.Client", "Client")
                        .WithMany("Vehicles")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AutoService.Data.Entities.VehicleData.VehicleFuelType", "FuelType")
                        .WithMany()
                        .HasForeignKey("FuelTypeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("AutoService.Data.Entities.VehicleData.TransmissionType", "TransmissionType")
                        .WithMany()
                        .HasForeignKey("TransmissionTypeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("AutoService.Data.Entities.VehicleData.VehicleType", "VehicleType")
                        .WithMany()
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Client");

                    b.Navigation("FuelType");

                    b.Navigation("TransmissionType");

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("AutoService.Data.Entities.VehicleData.VehicleServiceRecord", b =>
                {
                    b.HasOne("AutoService.Data.Entities.VehicleData.Vehicle", "Vehicle")
                        .WithMany("Records")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("AutoService.Data.Entities.UserData.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("AutoService.Data.Entities.UserData.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("AutoService.Data.Entities.UserData.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("AutoService.Data.Entities.UserData.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoService.Data.Entities.UserData.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("AutoService.Data.Entities.UserData.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AutoService.Data.Entities.ServiceData.Appointment", b =>
                {
                    b.Navigation("Request")
                        .IsRequired();
                });

            modelBuilder.Entity("AutoService.Data.Entities.ServiceData.Request", b =>
                {
                    b.Navigation("ServiceRequests");
                });

            modelBuilder.Entity("AutoService.Data.Entities.ServiceData.Service", b =>
                {
                    b.Navigation("ServiceRequests");

                    b.Navigation("ServicesPerformeds");
                });

            modelBuilder.Entity("AutoService.Data.Entities.UserData.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("AutoService.Data.Entities.VehicleData.Vehicle", b =>
                {
                    b.Navigation("Records");

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("AutoService.Data.Entities.VehicleData.VehicleServiceRecord", b =>
                {
                    b.Navigation("ServicesPerformeds");
                });

            modelBuilder.Entity("AutoService.Data.Entities.ClientData.Client", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Requests");

                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
